FROM openjdk:8
ADD microservicios-backend-retoibm-1.0.0-SNAPSHOT.jar microservicios-backend-retoibm-1.0.0-SNAPSHOT.jar
EXPOSE 3081
ENTRYPOINT ["java", "-jar", "microservicios-backend-retoibm-1.0.0-SNAPSHOT.jar"]